#!/bin/bash
# file: bootstrap.d/lib/brew_helper.sh

# ... (保留之前的 select_mirror 和 export_mirror_vars 函数) ...

# --- [新] 函数: 初始化环境文件 (覆写模式) ---
# 职责: 创建全新的 .env 文件，定义基础变量 (MY_LOCAL_ENV) 和 Brew 路径
# 参数 $1: brew 二进制路径
init_env_file() {
    local brew_bin_path="$1"
    
    echo "[BREW_HELPER] Initializing environment file at $ENV_FILE ..."
    mkdir -p "$ENV_DIR"

    # 注意: 这里使用 > (覆写)，确保每次 04_brew 运行时都是干净的状态
    cat > "$ENV_FILE" <<EOF
# Generated by yadm bootstrap (04_brew)
# Date: $(date)

# 1. Export Self Path (方便脚本引用自己)
export MY_LOCAL_ENV="$ENV_FILE"

# 2. Homebrew Mirror Settings
$(env | grep "^HOMEBREW_" | sed 's/^/export /')

# 3. Initialize Homebrew (PATH setup)
if [ -x "$brew_bin_path" ]; then
    eval "\$($brew_bin_path shellenv)"
fi
EOF
    echo "[BREW_HELPER] Environment file initialized."
}

# --- [新] 函数: 追加环境变量 (追加模式) ---
# 职责: 供 08_shell 或 10_vim 等后续脚本使用，添加新的变量
# 参数 $1: 变量名, $2: 变量值
append_env_var() {
    local key="$1"
    local value="$2"
    
    # 幂等性检查: 防止重复添加
    if grep -q "export $key=" "$ENV_FILE"; then
        echo "[BREW_HELPER] Update $key in .env"
        # 使用 sed 替换现有行 (适配 Linux 和 macOS 的 sed 差异比较麻烦，这里用简易追加兜底，或者建议手动管理)
        # 为了简单起见，这里假设用户不会频繁改值，或者允许重复 export (shell 取最后一条)
        echo "export $key=\"$value\"" >> "$ENV_FILE"
    else
        echo "[BREW_HELPER] Appending $key to .env"
        echo "export $key=\"$value\"" >> "$ENV_FILE"
    fi
}

# --- [修改] 通用安装逻辑 ---
run_brew_install_logic() {
    local target_brew_bin="$1"
    
    # 1. 选择源
    select_mirror
    
    # ... (保留安装检查逻辑) ...
    
    # 执行安装...
    if [ "$need_install" = true ]; then
        # ... (保留安装命令) ...
    fi
    
    # 4. 生成环境文件 (调用新的 init_env_file)
    if [ -x "$target_brew_bin" ]; then
        init_env_file "$target_brew_bin"  # <--- 关键修改
        
        # 5. 加载到当前 Shell
        eval "$("$target_brew_bin" shellenv)"
    else
        echo "[BREW_HELPER] CRITICAL: Installation finished but binary not found."
        exit 1
    fi
}
