#!/bin/bash
# file: bootstrap.d/lib/brew_helper.sh

# 定义配置文件路径
ENV_FILE="$HOME/.local/.env"
ENV_DIR="$(dirname "$ENV_FILE")"

# 定义安装器 URL
INSTALL_SCRIPT_URL="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"

# --- 函数: 选择镜像源 ---
select_mirror() {
    # 默认值
    MIRROR_CHOICE="Official"
    
    # 判读是否需要交互
    # 如果设置了 NONINTERACTIVE 或者 当前没有 TTY 设备，则跳过选择
    if [[ "${NONINTERACTIVE:-}" == "true" ]] || [[ ! -t 0 ]]; then
        echo "[BREW_HELPER] Non-interactive mode detected. Using default source: $MIRROR_CHOICE"
    else
        echo "------------------------------------------------"
        echo "Select Homebrew Mirror Source:"
        echo "1) USTC     (University of Science and Technology of China) [Recommended for CN]"
        echo "2) Tsinghua (Tsinghua University) [Alternative for CN]"
        echo "3) Official (Global / Default)"
        echo "------------------------------------------------"
        read -r -p "Enter choice [1-3] (Default: 3): " choice
        
        case "$choice" in
            1) MIRROR_CHOICE="USTC" ;;
            2) MIRROR_CHOICE="Tsinghua" ;;
            *) MIRROR_CHOICE="Official" ;;
        esac
    fi

    echo "[BREW_HELPER] Selected Mirror: $MIRROR_CHOICE"
    export_mirror_vars "$MIRROR_CHOICE"
}

# --- 函数: 导出镜像环境变量 (用于当前会话和写入文件) ---
export_mirror_vars() {
    local source_name="$1"
    
    case "$source_name" in
        "USTC")
            export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.ustc.edu.cn/brew.git"
            export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.ustc.edu.cn/homebrew-core.git"
            export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles"
            export HOMEBREW_API_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles/api"
            ;;
        "Tsinghua")
            export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
            export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
            export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
            export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
            ;;
        *)
            # 官方源无需设置变量，留空即可，或者 unset 清理
            unset HOMEBREW_BREW_GIT_REMOTE
            unset HOMEBREW_CORE_GIT_REMOTE
            unset HOMEBREW_BOTTLE_DOMAIN
            unset HOMEBREW_API_DOMAIN
            ;;
    esac
}

# --- 函数: 生成 ~/.local/.env 文件 ---
generate_env_file() {
    local brew_bin_path="$1"
    
    echo "[BREW_HELPER] Generating environment file at $ENV_FILE ..."
    mkdir -p "$ENV_DIR"

    cat > "$ENV_FILE" <<EOF
# Generated by yadm bootstrap
# Date: $(date)

# 1. Export Self Path
export MY_LOCAL_ENV="$ENV_FILE"

# 2. Homebrew Mirror Settings
$(env | grep "^HOMEBREW_" | sed 's/^/export /')

# 3. Initialize Homebrew
if [ -x "$brew_bin_path" ]; then
    eval "\$($brew_bin_path shellenv)"
fi
EOF

    echo "[BREW_HELPER] Environment file updated."
}

# --- 函数: 通用安装/修复逻辑 ---
run_brew_install_logic() {
    local target_brew_bin="$1"
    
    # 1. 选择源
    select_mirror
    
    # 2. 检查是否需要安装
    local need_install=false
    
    if [ ! -x "$target_brew_bin" ]; then
        echo "[BREW_HELPER] Binary not found at $target_brew_bin."
        need_install=true
    else
        # 尝试运行一下检查是否损坏
        if ! "$target_brew_bin" --version >/dev/null 2>&1; then
             echo "[BREW_HELPER] Binary exists but appears broken."
             need_install=true
             # 注意：清理逻辑最好在 OS 特有脚本里做，或者在这里谨慎处理
        else
             echo "[BREW_HELPER] Homebrew is installed and healthy."
        fi
    fi
    
    # 3. 执行安装
    if [ "$need_install" = true ]; then
        echo "[BREW_HELPER] Starting installation..."
        # 传递 NONINTERACTIVE=1 给官方脚本，实现静默安装
        NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL $INSTALL_SCRIPT_URL)"
    fi
    
    # 4. 生成环境文件 (无论是否新装，都要刷新 env 文件以确保源配置是最新的)
    #    注意：如果上面安装失败，这里可能会找不到文件，所以再次检查
    if [ -x "$target_brew_bin" ]; then
        generate_env_file "$target_brew_bin"
        
        # 5. 加载到当前 Shell，供后续脚本使用
        eval "$("$target_brew_bin" shellenv)"
    else
        echo "[BREW_HELPER] CRITICAL: Installation finished but binary not found."
        exit 1
    fi
}
