#!/bin/bash
# file: bootstrap.d/lib/env_helper.sh
#
# 目标：为各平台 bootstrap 提供用户级 shell 环境配置的生成工具。
# 结果：~/.local/.env 保存共享环境设置并加载 ~/.local/env.d 中的本地环境片段。

# 定义主环境文件和模块化配置目录
ENV_FILE="$HOME/.local/.env"
ENV_DIR="$(dirname "$ENV_FILE")"
ENV_D_DIR="$HOME/.local/env.d"

# --- 函数: 初始化环境文件 (覆写模式) ---
# 职责: 在 00_init 阶段调用
# 1. 创建目录结构 (包括 env.d)
# 2. 创建全新的 .env 文件，写入头部信息
reset_env_file() {
    echo "[ENV_HELPER] Resetting environment file structure..."
    
    # 确保主目录和模块化目录都存在
    mkdir -p "$ENV_DIR"
    mkdir -p "$ENV_D_DIR"
    chmod 700 "$ENV_D_DIR"

    echo "[ENV_HELPER] Overwriting $ENV_FILE ..."
    cat > "$ENV_FILE" <<EOF
# Generated by yadm bootstrap (00_init)
# Date: $(date)
# This file contains XDG Base Directory definitions and Global Environment Variables.

# 1. Export Self Path & Config Dir
export MY_LOCAL_ENV="\$HOME/.local/.env"
export MY_LOCAL_ENV_D="\$HOME/.local/env.d"

EOF
}

# --- 函数: 向环境文件写入 XDG 配置 (追加模式) ---
# 职责: 写入 XDG 变量，并确保对应的目录存在
# 参数: 接收一段文本作为 XDG 配置内容
write_xdg_config() {
    local xdg_content="$1"

    echo "[ENV_HELPER] Writing XDG configurations..."
    {
        echo ""
        echo "# 2. XDG Base Directories"
        echo "$xdg_content"
    } >> "$ENV_FILE"
    
    # 立即生效一遍，以便后续 mkdir 使用这些变量
    # 注意：这里临时 eval，仅为了当前脚本创建目录使用，不会影响父 shell
    eval "$xdg_content"
    
    # 确保目录存在
    echo "[ENV_HELPER] Ensuring XDG directories exist..."
    
    # 定义需要检查的变量名列表
    local vars=(
        "XDG_DATA_HOME"
        "XDG_CONFIG_HOME"
        "XDG_STATE_HOME"
        "XDG_CACHE_HOME"
        "XDG_RUNTIME_DIR"
        "XDG_DOCUMENTS_DIR"
        "XDG_DOWNLOAD_DIR"
        "XDG_MUSIC_DIR"
        "XDG_PICTURES_DIR"
        "XDG_PUBLICSHARE_DIR"
        "XDG_TEMPLATES_DIR"
        "XDG_VIDEOS_DIR"
    )

    for var in "${vars[@]}"; do
        # 使用间接引用获取变量值
        local dir_path="${!var}"
        if [ -n "$dir_path" ]; then
            # Linux XDG_RUNTIME_DIR (normally /run/user/$UID) is managed by the
            # login/session manager. Do not try to create it as an unprivileged
            # bootstrap process; continue creating the user-owned XDG folders.
            if [ "$var" = "XDG_RUNTIME_DIR" ] && [[ "$dir_path" == /run/user/* ]]; then
                if [ ! -d "$dir_path" ]; then
                    echo "  -> Runtime directory is session-managed and not present: $dir_path"
                fi
                continue
            fi
            if [ ! -d "$dir_path" ]; then
                echo "  -> Creating: $dir_path"
                mkdir -p "$dir_path"
            fi
        fi
    done
}

# --- 函数: 追加通用变量 (供 04_brew 等使用) ---
# 参数 $1: 标题注释
# 参数 $2: 内容
append_to_env() {
    local section_title="$1"
    local content="$2"
    
    echo "[ENV_HELPER] Appending '$section_title' to .env"
    {
        echo ""
        echo "# $section_title"
        echo "$content"
    } >> "$ENV_FILE"
}

# --- 函数: 在主环境文件末尾加载本机/工具环境片段 ---
# Keep this block Bash-compatible because bootstrap scripts also source .local/.env.
append_env_fragments_loader() {
    cat >> "$ENV_FILE" <<'EOF'

# Load local environment fragments after the shared XDG and Homebrew settings.
# Bootstrap scripts set ZDOT_SKIP_LOCAL_ENV_D to avoid importing user secrets.
if [[ -z "${ZDOT_SKIP_LOCAL_ENV_D:-}" && -n "${MY_LOCAL_ENV_D:-}" && -d "$MY_LOCAL_ENV_D" ]]; then
    __zdot_load_local_env_d() {
        local env_file
        if [[ -n "${ZSH_VERSION:-}" ]]; then
            setopt local_options null_glob
        fi
        for env_file in "$MY_LOCAL_ENV_D"/*; do
            [[ -f "$env_file" ]] || continue
            . "$env_file"
        done
    }
    __zdot_load_local_env_d
    unset -f __zdot_load_local_env_d
fi
EOF
}

# --- [新] 函数: 创建模块化应用配置 ---
# 职责: 供 Justfile 或其他安装脚本调用，生成独立的 env 文件
# 参数 $1: 文件名 (例如 go.env)
# 参数 $2: 内容
write_app_env() {
    local filename="$1"
    local content="$2"
    local target_file="$ENV_D_DIR/$filename"
    
    echo "[ENV_HELPER] Creating app config: $target_file"
    
    cat > "$target_file" <<EOF
# Generated for $filename
$content
EOF
    chmod 600 "$target_file"
}
