#!/bin/bash
# file: bootstrap.d/lib/zsh_helper.sh
#
# 目标：生成 Zsh 使用的用户级启动入口。
# 结果：~/.zshenv 加载本地环境和托管 Zsh 配置，使工具环境对所有 Zsh shell 生效。

setup_zshenv() {
    local target_zdotdir="$1"
    local target_file="$HOME/.zshenv"
    local target_zdotdir_expr="$target_zdotdir"

    # Keep generated startup files portable across machines and account names.
    if [[ "$target_zdotdir" == "$HOME" ]]; then
        target_zdotdir_expr='\$HOME'
    elif [[ "$target_zdotdir" == "$HOME/"* ]]; then
        target_zdotdir_expr="\$HOME/${target_zdotdir#"$HOME"/}"
    fi

    echo "[ZSH_HELPER] Configuring entry point at $target_file ..."

    # --- 1. 检查文件冲突与处理 ---
    if [ -f "$target_file" ]; then
        # 默认动作
        local action="rename"

        # bootstrap 自己生成的入口文件可以安全覆写，避免重复执行时不断备份。
        if grep -Fqx '# Generated by yadm bootstrap' "$target_file"; then
            action="overwrite"
        # 非交互模式下备份未知来源的文件；交互模式下由用户选择。
        elif [[ "${NONINTERACTIVE:-}" != "true" ]] && [ -t 0 ]; then
            echo "------------------------------------------------"
            echo "Found existing $target_file"
            echo "Would you like to Overwrite it or Rename (backup) it?"
            echo "[O]verwrite  : Replace the file completely."
            echo "[R]ename     : Rename existing to .zshenv.bak.<timestamp> (Default)"
            echo "------------------------------------------------"
            read -r -p "Choice [O/r]: " choice

            if [[ "$choice" =~ ^[oO]$ ]]; then
                action="overwrite"
            fi
        else
            echo "[ZSH_HELPER] Non-interactive or existing file found. Defaulting to backup (Rename)."
        fi

        # 执行动作
        if [ "$action" == "rename" ]; then
            local timestamp=$(date +%Y%m%d_%H%M%S)
            local backup_file="${target_file}.bak.${timestamp}"
            mv "$target_file" "$backup_file"
            echo "[ZSH_HELPER] Backed up existing file to $backup_file"
        else
            echo "[ZSH_HELPER] Overwriting existing file..."
        fi
    fi

    # --- 2. 生成新内容 ---
    # EOF 不带引号以便展开生成时变量；运行时变量使用转义的 \$。
    cat > "$target_file" <<EOF
# Generated by yadm bootstrap
# This file serves as the entry point for Zsh.

# 1. Load Local Environment (Generated by bootstrap 00_init and 04_brew).
# This provides XDG directories and Homebrew's environment before other config loads.
if [[ -f "\$HOME/.local/.env" ]]; then
    source "\$HOME/.local/.env"
fi

# 2. Set ZDOTDIR
# Redirects Zsh to load configuration from the managed directory.
export ZDOTDIR="$target_zdotdir_expr"

# 3. Source the nested zshenv if it exists
if [[ -f "\$ZDOTDIR/.zshenv" ]]; then
    source "\$ZDOTDIR/.zshenv"
fi
EOF

    echo "[ZSH_HELPER] ~/.zshenv updated. ZDOTDIR -> $target_zdotdir"
}
