#!/bin/bash
# file: bootstrap.d/lib/zsh_helper.sh

# --- 函数: 生成并配置 ~/.zshenv ---
# 参数 $1: 指定的 ZDOTDIR 路径 (例如: $HOME/.config/zsh/zdotdir.Darwin)
setup_zshenv() {
    local target_zdotdir="$1"
    local target_file="$HOME/.zshenv"
    local local_env_file="$HOME/.local/.env"

    echo "[ZSH_HELPER] Configuring entry point at $target_file ..."

    # --- 1. 检查文件冲突与处理 ---
    if [ -f "$target_file" ]; then
        # 默认动作
        local action="rename"

        # 检查是否为非交互模式
        # 如果是交互模式，询问用户
        if [[ "${NONINTERACTIVE:-}" != "true" ]] && [ -t 0 ]; then
            echo "------------------------------------------------"
            echo "Found existing $target_file"
            echo "Would you like to Overwrite it or Rename (backup) it?"
            echo "[O]verwrite  : Replace the file completely."
            echo "[R]ename     : Rename existing to .zshenv.bak.<timestamp> (Default)"
            echo "------------------------------------------------"
            read -r -p "Choice [O/r]: " choice

            if [[ "$choice" =~ ^[oO]$ ]]; then
                action="overwrite"
            fi
        else
            echo "[ZSH_HELPER] Non-interactive or existing file found. Defaulting to backup (Rename)."
        fi

        # 执行动作
        if [ "$action" == "rename" ]; then
            local timestamp=$(date +%Y%m%d_%H%M%S)
            local backup_file="${target_file}.bak.${timestamp}"
            mv "$target_file" "$backup_file"
            echo "[ZSH_HELPER] Backed up existing file to $backup_file"
        else
            echo "[ZSH_HELPER] Overwriting existing file..."
        fi
    fi

    # --- 2. 生成新内容 ---
    # 注意: EOF 不带引号，允许 $local_env_file 等变量在生成时展开
    # 但是: $ZDOTDIR 需要在运行时展开，所以使用转义 \$
    cat > "$target_file" <<EOF
# Generated by yadm bootstrap
# This file serves as the entry point for Zsh.

# 1. Load Local Environment (Generated by bootstrap 00_init)
# This sets HOMEBREW_PREFIX and PATH before any other config loads.
if [[ -f "$local_env_file" ]]; then
    source "$local_env_file"
fi

# 2. Set ZDOTDIR
# Redirects Zsh to load configuration from the managed directory.
export ZDOTDIR="$target_zdotdir"

# 3. Source the nested zshenv if it exists
if [[ -f "\$ZDOTDIR/.zshenv" ]]; then
    source "\$ZDOTDIR/.zshenv"
fi
EOF

    echo "[ZSH_HELPER] ~/.zshenv updated. ZDOTDIR -> $target_zdotdir"
}
